### PR TITLE
Ensure that Thoth.Json.Net references the minimum allowed version of Newtonsoft.Json

### LINKED ISSUE #18: Should Thoth.Json.Net.dll in the nupkg lib reference the minimum dependency version of Newtonsoft.Json?
_Reposting this issue here as originally submitted in the [old Issues repos](https://github.com/MangelMaxime/Thoth/issues/147)._

Hi Thothers!

I've tried to figure this out, but failed, so hoping someone in here will have the knowledge.

I have a problem which I *think* stems from the fact that the [`Thoth.Json.Net`](https://www.nuget.org/packages/Thoth.Json.Net/3.0.0) nuspec specifies `<dependency id="Newtonsoft.Json" version="11.0.2" />` but the  `nupkg/lib/netstandard2.0/Thoth.Json.Net.dll` references version `12.0.0.0`.

Here is the nuspec for 3.0.0:
image

And here is the lib reference (via ILSpy):
image

In our case, `Thoth.Json.Net` is a dependency of our first assembly A and then we reference A from our second assembly B.  We then reference assembly B from a web project, where the dependencies are managed by Nuget, not Paket.  In this situation, `Thoth.Json.Net` is a transitive dependency of our web application and as a result, so is `Newtonsoft.Json`.  Nuget correctly identifies this, reads the nuspec for Thoth and based on that decides we are fine with version `11.0.2` of `Newtonsoft.Json` (I think Nuget defaults to the earliest version of the dependency?).  However, at runtime our web application fails because `Thoth.Json.Net` tries to load version `12.0.0.0`.

I've done a bunch of Googling, but have been unable to determine how I'm supposed to handle this in the .NET Core world (in the old world I might have tried a ["downgrade" assembly binding](https://stackoverflow.com/a/17108316/418492)).  On the surface it would seem sensible to me that the lib distribution of `Thoth.Json.Net` should reference the minimum version of it's dependencies in order to avoid this, but maybe I'm missing something and this is a scenario that should be fine?  If so, does anyone know the incantations I need to mumble?

*I'm currently working around this by adding version 12 of Newtonsoft as a top level PackageReference in my web project, but that is not ideal.*

### PR DESCRIPTION
**Pull request by bentayloruk**
Today I learnt about [`lowest_matching`](https://fsprojects.github.io/Paket/nuget-dependencies.html#Resolver-strategy-for-direct-dependencies) in Paket and I think it does what we want to fix #18.  It seems to have worked for me and I've also successfully run the tests on OSX.   In addition I did a `Publish` build and confirmed that the `nuspec` seemed to retain the correct `11.0.2` and up inclusive version.

Please review and let me know if it works for you!

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Thank you, I will fix a few other issues before releasing the new version.

**Comment by MangelMaxime** [comment]
I am trying to improve the deps requirement of Thoth.Json.Net due to changes needed to fix another issue.

Before my changes:
Capture d’écran 2019-06-07 à 15 53 37

After my changes:
Capture d’écran 2019-06-07 à 17 17 08

The second looks more correct to me because it's requiring `Fable.Core` only for `.NetStandard` and also don't use `0.0.0` as the version. But as I said I am not sure if by reworking the package generation I broke or no your fix...

Could you please check that version `3.5.0-beta-001` is still ok for your problem?

**Comment by bentayloruk** [comment]
Thanks for letting me know.  I will check the beta version now.

**Comment by bentayloruk** [comment]
I'm having some issues, but not sure why they are happening yet.  Will investigate.

Side question, 3.5.0 beta 1 is `1.0.0.0` in all of the assembly version attributes.  Is that intentional?
image

**Comment by MangelMaxime** [comment]
I don't think this is intentional, no it's not intentional... I am now using `paket.template` in file mode to generate the package it solves one of the problems but seems to create others... In theory, Steffen should be able to help me understand the situation and fix it. 

I will ping you again to check... Thank you for taking the time to test the beta package.

**Comment by bentayloruk** [comment]
I am in a very deep rabbit hole and am currently unable to verify if this will eventually help resolve my issue.  I'm fighting a battle between the different resolution algorithms of paket and nuget and also the fact that I end up packaging the entire thing into a [SCD](https://docs.microsoft.com/en-us/dotnet/core/deploying/#self-contained-deployments-scd).  Basically, I don't think I'm going to have this untangled today and I'm travelling then for a few days.

I can confirm that Thoth.Json.Net does now reference the lowest version of Newtonsoft.Json, but I'm not sure if this will end up helping my situation.  To be honest I'm not longer sure if it should reference the lowest version!  It seems sensible, but maybe one of the dependency lords can chime in to confirm.

Of course I will update when I get everything sorted.

**Pull request merged**
